version: '3'
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  web:
    build: ./frontend
    volumes:
      - '.:/minimundistances'
      - '/minimundistances/node_modules'
    ports:
      - '7000:3000'
    environment:
      NODE_ENV: development    